apiVersion: v1
kind: Service
metadata:
  name: stats-preview-card-component
  namespace: default
spec:
  selector:
    app: stats-preview-card-component-app
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
